// Currency data extracted from Money Tracker database.json
export type Currency = {
  iso: string;
  name: string;
  symbol: string;
  decimals: number;
};

export const CURRENCIES: Currency[] = [
  { iso: "AED", name: "UAE Dirham", symbol: "د.إ", decimals: 2 },
  { iso: "AFN", name: "Afghan Afghani", symbol: "؋", decimals: 0 },
  { iso: "ALL", name: "Albanian lek", symbol: "L", decimals: 0 },
  { iso: "AMD", name: "Armenian Dram", symbol: "֏", decimals: 0 },
  {
    iso: "ANG",
    name: "Netherlands Antillian Guilder",
    symbol: "ƒ",
    decimals: 2,
  },
  { iso: "AOA", name: "Angolan Kwanza", symbol: "Kz", decimals: 2 },
  { iso: "ARS", name: "Argentine Peso", symbol: "$", decimals: 2 },
  { iso: "AUD", name: "Australian Dollar", symbol: "$", decimals: 2 },
  { iso: "AWG", name: "Aruban Florin", symbol: "ƒ", decimals: 2 },
  { iso: "AZN", name: "Azerbaijanian Manat", symbol: "ман", decimals: 2 },
  { iso: "BAM", name: "Convertible Marks", symbol: "KM", decimals: 2 },
  { iso: "BBD", name: "Barbados Dollar", symbol: "$", decimals: 2 },
  { iso: "BDT", name: "Bangladeshi Taka", symbol: "৳", decimals: 2 },
  { iso: "BGN", name: "Bulgarian Lev", symbol: "лв", decimals: 2 },
  { iso: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", decimals: 3 },
  { iso: "BIF", name: "Burundi Franc", symbol: "FBu", decimals: 0 },
  { iso: "BMD", name: "Bermudian Dollar", symbol: "$", decimals: 2 },
  { iso: "BND", name: "Brunei Dollar", symbol: "$", decimals: 2 },
  { iso: "BOB", name: "Boliviano Mvdol", symbol: "$b", decimals: 2 },
  { iso: "BRL", name: "Brazilian Real", symbol: "R$", decimals: 2 },
  { iso: "BSD", name: "Bahamian Dollar", symbol: "$", decimals: 2 },
  { iso: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", decimals: 2 },
  { iso: "BWP", name: "Botswana Pula", symbol: "P", decimals: 2 },
  { iso: "BYN", name: "Belarussian Ruble", symbol: "Br", decimals: 2 },
  { iso: "BZD", name: "Belize Dollar", symbol: "BZ$", decimals: 2 },
  { iso: "CAD", name: "Canadian Dollar", symbol: "$", decimals: 2 },
  { iso: "CDF", name: "Congolese Franc", symbol: "Fr.", decimals: 2 },
  { iso: "CHF", name: "Swiss Franc", symbol: "CHF", decimals: 2 },
  { iso: "CLP", name: "Chilean Peso", symbol: "$", decimals: 0 },
  { iso: "CNY", name: "Chinese Yuan Renminbi", symbol: "¥", decimals: 2 },
  { iso: "COP", name: "Colombian Peso", symbol: "$", decimals: 0 },
  { iso: "CRC", name: "Costa Rican Colon", symbol: "₡", decimals: 0 },
  { iso: "CUP", name: "Cuban Peso", symbol: "₱", decimals: 2 },
  { iso: "CUC", name: "Cuban Convertible Peso", symbol: "$", decimals: 2 },
  { iso: "CVE", name: "Cape Verde Escudo", symbol: "Esc", decimals: 2 },
  { iso: "CZK", name: "Czech Koruna", symbol: "Kč", decimals: 2 },
  { iso: "DJF", name: "Djibouti Franc", symbol: "Fdj", decimals: 0 },
  { iso: "DKK", name: "Danish Krone", symbol: "kr", decimals: 2 },
  { iso: "DOP", name: "Dominican Peso", symbol: "RD$", decimals: 2 },
  { iso: "DZD", name: "Algerian Dinar", symbol: "د.ج", decimals: 2 },
  { iso: "EGP", name: "Egyptian Pound", symbol: "£", decimals: 2 },
  { iso: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", decimals: 2 },
  { iso: "ETB", name: "Ethiopian Birr", symbol: "Br.", decimals: 0 },
  { iso: "EUR", name: "Euro", symbol: "€", decimals: 2 },
  { iso: "FJD", name: "Fiji Dollar", symbol: "$", decimals: 2 },
  { iso: "FKP", name: "Falkland Islands Pound", symbol: "£", decimals: 2 },
  { iso: "GBP", name: "British Pound Sterling", symbol: "£", decimals: 2 },
  { iso: "GEL", name: "Georgian Lari", symbol: "ლ", decimals: 2 },
  { iso: "GHS", name: "Ghana Cedi", symbol: "₵", decimals: 2 },
  { iso: "GIP", name: "Gibraltar Pound", symbol: "£", decimals: 2 },
  { iso: "GMD", name: "Ghambian Dalasi", symbol: "D", decimals: 2 },
  { iso: "GNF", name: "Guinea Franc", symbol: "GFr", decimals: 0 },
  { iso: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", decimals: 2 },
  { iso: "GYD", name: "Guyana Dollar", symbol: "$", decimals: 0 },
  { iso: "HKD", name: "Hong Kong Dollar", symbol: "$", decimals: 2 },
  { iso: "HNL", name: "Honduran Lempira", symbol: "L", decimals: 2 },
  { iso: "HRK", name: "Croatian Kuna", symbol: "kn", decimals: 2 },
  { iso: "HTG", name: "Haitian Gourde", symbol: "G", decimals: 2 },
  { iso: "HUF", name: "Hungarian Forint", symbol: "Ft", decimals: 2 },
  { iso: "IDR", name: "Indonesian Rupiah", symbol: "Rp", decimals: 0 },
  { iso: "ILS", name: "Israeli New Sheqel", symbol: "₪", decimals: 2 },
  { iso: "INR", name: "Indian Rupee", symbol: "₹", decimals: 2 },
  { iso: "IQD", name: "Iraqi Dinar", symbol: "ع.د", decimals: 0 },
  { iso: "IRR", name: "Iranian Rial", symbol: "﷼", decimals: 2 },
  { iso: "ISK", name: "Iceland Krona", symbol: "kr", decimals: 0 },
  { iso: "JMD", name: "Jamaican Dollar", symbol: "J$", decimals: 2 },
  { iso: "JOD", name: "Jordanian Dinar", symbol: "د.ا", decimals: 3 },
  { iso: "JPY", name: "Japanese Yen", symbol: "¥", decimals: 0 },
  { iso: "KES", name: "Kenyan Shilling", symbol: "Sh", decimals: 2 },
  { iso: "KGS", name: "Kyrgyzstani Som", symbol: "лв", decimals: 2 },
  { iso: "KHR", name: "Cambodian Riel", symbol: "៛", decimals: 2 },
  { iso: "KMF", name: "Comoro Franc", symbol: "CF", decimals: 0 },
  { iso: "KPW", name: "North Korean Won", symbol: "₩", decimals: 0 },
  { iso: "KRW", name: "South Korean Won", symbol: "₩", decimals: 0 },
  { iso: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", decimals: 3 },
  { iso: "KYD", name: "Cayman Islands Dollar", symbol: "$", decimals: 2 },
  { iso: "KZT", name: "Kazakhstani Tenge", symbol: "₸", decimals: 2 },
  { iso: "LAK", name: "Lao Kip", symbol: "₭", decimals: 0 },
  { iso: "LBP", name: "Lebanese Pound", symbol: "ل.ل", decimals: 0 },
  { iso: "LKR", name: "Sri Lanka Rupee", symbol: "රු", decimals: 2 },
  { iso: "LRD", name: "Liberian Dollar", symbol: "$", decimals: 2 },
  { iso: "LSL", name: "Lesotho Loti", symbol: "L", decimals: 2 },
  { iso: "LYD", name: "Libyan Dinar", symbol: "ل.د", decimals: 3 },
  { iso: "MAD", name: "Moroccan Dirham", symbol: "د.م.", decimals: 2 },
  { iso: "MDL", name: "Moldovan Leu", symbol: "L", decimals: 2 },
  { iso: "MGA", name: "Malagasy Ariary", symbol: "Ar", decimals: 0 },
  { iso: "MKD", name: "Macedonian Denar", symbol: "ден", decimals: 2 },
  { iso: "MMK", name: "Burmese Kyat", symbol: "Ks", decimals: 0 },
  { iso: "MNT", name: "Mongolian Tugrik", symbol: "₮", decimals: 0 },
  { iso: "MOP", name: "Macanese Pataca", symbol: "P", decimals: 2 },
  { iso: "MRO", name: "Mauritanian Ouguiya", symbol: "UM", decimals: 0 },
  { iso: "MUR", name: "Mauritius Rupee", symbol: "₨", decimals: 0 },
  { iso: "MVR", name: "Maildivian Rufiyaa", symbol: ".ރ", decimals: 2 },
  { iso: "MWK", name: "Malawian Kwacha", symbol: "MK", decimals: 2 },
  { iso: "MXN", name: "Mexican Peso", symbol: "$", decimals: 2 },
  { iso: "MYR", name: "Malaysian Ringgit", symbol: "RM", decimals: 2 },
  { iso: "MZN", name: "Mozambican Metical", symbol: "MT", decimals: 2 },
  { iso: "NAD", name: "Namibian Dollar", symbol: "$", decimals: 2 },
  { iso: "NGN", name: "Nigeria Naira", symbol: "₦", decimals: 2 },
  { iso: "NIO", name: "Nicaraguan Cordoba Oro", symbol: "C$", decimals: 2 },
  { iso: "NOK", name: "Norwegian Krone", symbol: "kr", decimals: 2 },
  { iso: "NPR", name: "Nepalese Rupee", symbol: "₨", decimals: 2 },
  { iso: "NZD", name: "New Zealand Dollar", symbol: "$", decimals: 2 },
  { iso: "OMR", name: "Omani Rial", symbol: "ر.ع.", decimals: 3 },
  { iso: "PAB", name: "Panamanian Balboa", symbol: "B/.", decimals: 2 },
  { iso: "PEN", name: "Peruvian Nuevo Sol", symbol: "S/.", decimals: 2 },
  { iso: "PGK", name: "Papua New Guinean Kina", symbol: "K", decimals: 2 },
  { iso: "PHP", name: "Philippine Peso", symbol: "₱", decimals: 2 },
  { iso: "PKR", name: "Pakistan Rupee", symbol: "₨", decimals: 0 },
  { iso: "PLN", name: "Polish Zloty", symbol: "zł", decimals: 2 },
  { iso: "PYG", name: "Paraguayan Guarani", symbol: "₲", decimals: 0 },
  { iso: "QAR", name: "Qatari Rial", symbol: "ر.ق", decimals: 2 },
  { iso: "RON", name: "Romanian Leu", symbol: "lei", decimals: 2 },
  { iso: "RSD", name: "Serbian Dinar", symbol: "Дин.", decimals: 0 },
  { iso: "RUB", name: "Russian Ruble", symbol: "руб", decimals: 2 },
  { iso: "RWF", name: "Rwanda Franc", symbol: "R₣", decimals: 0 },
  { iso: "SAR", name: "Saudi Riyal", symbol: "ر.س", decimals: 2 },
  { iso: "SBD", name: "Solomon Islands Dollar", symbol: "$", decimals: 2 },
  { iso: "SCR", name: "Seychelles Rupee", symbol: "₨", decimals: 2 },
  { iso: "SDG", name: "Sudanese Pound", symbol: "£", decimals: 2 },
  { iso: "SEK", name: "Swedish Krona", symbol: "kr", decimals: 2 },
  { iso: "SGD", name: "Singapore Dollar", symbol: "$", decimals: 2 },
  { iso: "SHP", name: "Saint Helena Pound", symbol: "£", decimals: 2 },
  { iso: "SLL", name: "Sierra Leonean Leone", symbol: "Le", decimals: 0 },
  { iso: "SOS", name: "Somali Shilling", symbol: "Sh", decimals: 0 },
  { iso: "SRD", name: "Surinamese Dollar", symbol: "$", decimals: 2 },
  {
    iso: "STD",
    name: "São Tomé and Príncipe Dobra",
    symbol: "Db",
    decimals: 0,
  },
  { iso: "SVC", name: "El Salvador Colon US Dollar", symbol: "$", decimals: 2 },
  { iso: "SYP", name: "Syrian Pound", symbol: "ل.س", decimals: 0 },
  { iso: "SZL", name: "Swazi Lilangeni", symbol: "L", decimals: 2 },
  { iso: "THB", name: "Thai Baht", symbol: "฿", decimals: 2 },
  { iso: "TJS", name: "Tajikistani Somoni", symbol: "SM", decimals: 2 },
  { iso: "TMT", name: "Turkmenistan Manat", symbol: "m", decimals: 2 },
  { iso: "TND", name: "Tunisian Dinar", symbol: "د.ت", decimals: 3 },
  { iso: "TOP", name: "Tongan Pa'anga", symbol: "T$", decimals: 2 },
  { iso: "TRY", name: "Turkish Lira", symbol: "₺", decimals: 2 },
  {
    iso: "TTD",
    name: "Trinidad and Tobago Dollar",
    symbol: "TT$",
    decimals: 2,
  },
  { iso: "TWD", name: "New Taiwan Dollar", symbol: "NT$", decimals: 2 },
  { iso: "TZS", name: "Tanzanian Shilling", symbol: "Sh", decimals: 0 },
  { iso: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", decimals: 2 },
  { iso: "UGX", name: "Uganda Shilling", symbol: "Sh", decimals: 0 },
  { iso: "USD", name: "US Dollar", symbol: "$", decimals: 2 },
  { iso: "UYU", name: "Uruguayan Peso", symbol: "$U", decimals: 2 },
  { iso: "UZS", name: "Uzbekistan Som", symbol: "som", decimals: 0 },
  { iso: "VEF", name: "Venezuelan Bolivar Fuerte", symbol: "Bs", decimals: 2 },
  { iso: "VND", name: "Vietnamese Dong", symbol: "₫", decimals: 0 },
  { iso: "VUV", name: "Vanuatu Vatu", symbol: "Vt", decimals: 0 },
  { iso: "WST", name: "Samoan Tala", symbol: "T", decimals: 2 },
  { iso: "XAF", name: "CFA Franc BEAC", symbol: "", decimals: 0 },
  { iso: "XCD", name: "East Caribbean Dollar", symbol: "$", decimals: 2 },
  { iso: "XDR", name: "SDR", symbol: "", decimals: 2 },
  { iso: "XOF", name: "CFA Franc BCEAO", symbol: "", decimals: 0 },
  { iso: "XPF", name: "CFP Franc", symbol: "", decimals: 0 },
  { iso: "YER", name: "Yemeni Rial", symbol: "﷼", decimals: 0 },
  { iso: "ZAR", name: "South African Rand", symbol: "R", decimals: 2 },
  { iso: "ZMW", name: "Zambian Kwacha", symbol: "ZK", decimals: 2 },
  { iso: "ZWD", name: "Zimbabwe Dollar", symbol: "", decimals: 0 },
];

export function getCurrencyByIso(iso: string): Currency | undefined {
  return CURRENCIES.find((c) => c.iso === iso);
}

export function getCurrencySymbol(iso: string): string {
  const currency = getCurrencyByIso(iso);
  return currency?.symbol || iso;
}
